Allows filter to detect GIR classes
sipb/courseroad2 pull request #424
Opened 2020-12-02 22:32 UTC by w-nicole

Changed regex to detect more Subjects with Prereq for GIR classes.

2020-12-06 21:24 UTC, georgiashay requested changes
Everything works great!  Just one stylistic/best practices comment but ready to merge after that is addressed!

2020-12-06 21:24 UTC, georgiashay commented on src/components/ClassInfo.vue
> +        var IDMatcher = new RegExp('(^|[^\\da-zA-Z])' + currentID.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '(?![\\da-zA-Z])');
The IDMatcher variable is declared separately within the if and else blocks.  While this does work fine (Javascript will "hoist" the variable so it exists outside of the if statement), it is better practice/clearer to define this variable above the if statement (just "var IDMatcher;") and then assign to it within the if statement.

2020-12-17 20:19 UTC, w-nicole commented
I committed a new version of the code with the style changes. It's visible in Commits. Please let me know if there's anything else I should be fix, or if I didn't push the commit correctly. Thank you for all of your help!

2020-12-18 02:31 UTC, georgiashay commented
Thanks for making the changes!  I think it would be clearer to assign thisGIRAttr on one line inside the else statement (missed this the first time).  Again a minor thing, let me know if you think it is better the original way.

2020-12-29 22:02 UTC, georgiashay commented
Pushed lint to trigger Travis (just updated our testing so it doesn't stop working after the new year).  You'll need to pull these changes before working on it (git pull).  If you've already worked on it, commit your changes and then run git pull to get my updates.

2021-01-04 01:03 UTC, w-nicole commented
I changed the variable assignment to be in one line for the else statement.

2021-01-05 23:49 UTC, georgiashay commented
Everything looks good!  Merging

2021-01-05 23:49 UTC, merged